### ISSUE TITLE
Has no atttribute 'impulse' error - Ubuntu22

### ISSUE THREAD

**Issue by AlexanderGros** [righthalfplane/gr-extras#1]
Hello,

Wanted to try the impulse block  but got the following error:

__init__
    self.extras_uBuntu22_04_impulse_0 = extras_uBuntu22_04.impulse(1024, 5)
AttributeError: module 'gnuradio.extras_uBuntu22_04' has no attribute 'impulse'

**Comment by righthalfplane** [comment]
Sorry about that - they have several versions of their interface to gnuradio. It stopped working on some of the newer versions and their instructions to automatically convert to the new versions do not work. It is not too difficult to do by hand, but it is almost a complete rewrite. I just wish these idiots would learn to make things backward compatible. I have a 350,000 line Windows 98 program that still works with no problems. If the gnuradio people were in charge, I would have needed to do four rewrites in the last few years.
